site_name: Etienne's Bookmarks
site_url: https://bm.kerzo.ca/

nav:
  - "Accueil": index.md
  - "Bookmarks": bookmarks.md
  - "Horaire": horaire.md
  - "Cours":
      - "Bases de données 1": bd1.md
      - "Bases de données 2": bd2.md
      - "Développement Web 3": devweb3.md
      - "Piratage éthique": piratage.md
      - "Support technique": support.md
      - "Technologies émergentes": techno.md
  - "Pédagogie": pedagogie.md
  - "Karine": karine.md
  - "Humour": humour.md
  - "Maison": maison.md
  - "Outils":
      - "Documentation": documentation.md
      - "Données": donnees.md
      - "Git": git.md
      - "Langues": langues.md
      - "Développement": developpement.md
      - "Mac": mac.md
      - "Bâtir mac": buildmac.md
  - "Liste de lecture": readinglist.md
  - "Retraite": retraite.md
  - "Estrimont": estrimont.md
  - "Recettes":
      - "Livre de recettes": recettes/livre.md
      - "Anglais":
          - "Popover": recettes/popover.md
      - "Asiatique":
          - "Sauce arachide": recettes/sauce-arachide.md
      - "Français":
          - "Boeuf bourguignon": recettes/boeuf-bourguignon.md
          - "Pommes de terre à la bretonne": recettes/pommes-terre-bretonnes.md
      - "Indien":
          - "Curry de pois chiches": recettes/curry-pois-chiches.md
          - "Naan": recettes/naan.md  
          - "Dumpling bake": recettes/dumpling-bake.md  
      - "Italien":
          - "Carbonara": recettes/carbonara.md
          - "Soupe tortellini": recettes/soupe-tortellini.md
      - "Jamaïcain":
          - "Riz aux haricots": recettes/riz-aux-haricots.md
      - "Mexicain":
          - "Sauce Taco Bell": recettes/tacobellsauce.md  
      - "Québécois":
          - "Beans dans le sirop": recettes/beans.md
          - "Bouilli de porc": recettes/bouilli-de-porc.md
          - "Crêpes": recettes/crepes.md
          - "Eggs Newport": recettes/eggs-newport.md
          - "Muffins déjeuner": recettes/muffins-dejeuner.md
          - "Pain doré": recettes/pain-dore.md
          - "Roti à la Louise": recettes/roti-louise.md
          - "Soupe de pommes de terre et cheddar": recettes/soupe-patates-cheddar.md
          - "Soupe broccoli": recettes/soupebroccoli.md  
          - "Crème de patates": recettes/creme-de-patates.md
      - "Pains":
          - "No nead bread": recettes/pain.md
      - "Desserts":
          - "Carrés aux dattes": recettes/carres-aux-dattes.md
          - "Croustade aux pommes": recettes/croustade-pommes.md
          - "Gâteau graham": recettes/gateau-graham.md
          - "Gaufres": recettes/gaufres.md
          - "Grand-père dans le sirop": recettes/grand-pere.md
          - "Muffin avoine et chocolat": recettes/muffins-avoine-chocolat.md
          - "Pain aux bananes": recettes/pain-bananes.md
          - "Renversé aux fraises": recettes/renverse-aux-fraises.md

theme:
  name: material
  favicon: images/red-bookmark.png
  icon:
    logo: fontawesome/solid/bookmark
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.code.copy
    - toc.integrate
  language: fr
  palette:
    scheme: slate
    primary: deep purple
    accent: blue
plugins:
  - search: {}

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
